/*
 * JSP generated by Resin-3.1.12 (built Mon, 29 Aug 2011 03:22:08 PDT)
 */

package _jsp._task;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import com.sogou.qadev.service.cynthia.service.ProjectInvolveManager;
import com.sogou.qadev.service.cynthia.service.ErrorManager.ErrorType;
import com.sogou.qadev.service.cynthia.service.ErrorManager;
import com.sogou.qadev.service.cynthia.bean.Role;
import com.sogou.qadev.service.cynthia.bean.Action;
import com.sogou.qadev.service.cynthia.bean.Flow;
import com.sogou.qadev.service.cynthia.util.CynthiaUtil;
import com.sogou.qadev.service.cynthia.bean.Key;
import com.sogou.qadev.service.cynthia.factory.DataAccessFactory;
import com.sogou.qadev.service.cynthia.bean.UUID;
import com.sogou.qadev.service.cynthia.bean.Data;
import com.sogou.qadev.service.cynthia.bean.Template;
import com.sogou.qadev.service.cynthia.bean.Field;
import com.sogou.qadev.service.cynthia.bean.Option;
import com.sogou.qadev.service.cynthia.bean.Filter;
import com.sogou.qadev.service.cynthia.service.DataAccessSession;
import com.sogou.qadev.service.cynthia.util.ConfigUtil;
import org.w3c.dom.Document;
import com.sogou.qadev.service.cynthia.util.XMLUtil;
import org.w3c.dom.Node;
import java.util.*;
import com.sogou.qadev.service.cynthia.bean.Pair;
import com.sogou.qadev.service.cynthia.bean.Option.Forbidden;
import org.apache.commons.httpclient.HttpClient;
import org.apache.commons.httpclient.NameValuePair;
import org.apache.commons.httpclient.methods.PostMethod;
import org.apache.commons.httpclient.params.*;
import com.sogou.qadev.service.cynthia.bean.DataAccessAction;

public class _initstartactions__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;

  DataAccessFactory daf = DataAccessFactory.getInstance();
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/xml; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
	response.setHeader("Cache-Control","no-cache"); //Forces caches to obtain a new copy of the page from the origin server
	response.setHeader("Cache-Control","no-store"); //Directs caches not to store the page under any circumstance
	response.setDateHeader("Expires", 0); //Causes the proxy cache to see the page as "stale"
	response.setHeader("Pragma","no-cache"); //HTTP 1.0 backward compatibility
	
	out.clear();
	
	Long keyId = (Long)session.getAttribute("kid");
	Key key = (Key)session.getAttribute("key");

	if(keyId == null || keyId <= 0 || key == null){
		response.sendRedirect(ConfigUtil.getCynthiaWebRoot());
		return;
	}
	
	String templateIdStr = request.getParameter("templateId");
	if(templateIdStr == null){
		out.println(ErrorManager.getErrorXml(ErrorType.param_error));
		return;
	}
	
	UUID templateId = DataAccessFactory.getInstance().createUUID(templateIdStr);
	
	DataAccessSession das = DataAccessFactory.getInstance().createDataAccessSession(key.getUsername(), keyId);
	
	//get template
	Template template = das.queryTemplate(templateId);
	if(template == null){	
		out.println(ErrorManager.getErrorXml(ErrorType.template_not_found));
		return;
	}
	
	//get templateXml
	String templateXml = template.toXMLString();
	if(templateXml == null){
		out.println(ErrorManager.getErrorXml(ErrorType.template_xml_error));
		return;
	}
	
	//get flow
	Flow flow = das.queryFlow(template.getFlowId());
	if(flow == null){
		out.println(ErrorManager.getErrorXml(ErrorType.flow_not_found));
		return;
	}
	
	StringBuffer xmlb = new StringBuffer(64);
	xmlb.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
	
	xmlb.append("<root>");
	
	xmlb.append("<isError>false</isError>");
	xmlb.append("<isProTemplate>").append(String.valueOf(template.getTemplateConfig().isProjectInvolve())).append("</isProTemplate>");
	xmlb.append("<productInvolvedId>").append(String.valueOf(template.getTemplateConfig().getProductInvolveId())).append("</productInvolvedId>");
	xmlb.append("<projectInvolvedId>").append(String.valueOf(template.getTemplateConfig().getProjectInvolveId())).append("</projectInvolvedId>");
	
	xmlb.append(templateXml.substring(templateXml.indexOf("<template>")));
	
	//get actionArray
	Action[] actionArray = flow.queryUserNodeBeginActions(das.getUsername(), template.getId());
	
	if(actionArray == null || actionArray.length == 0){
		xmlb.append("<actions/>");
	}else{
		xmlb.append("<actions>");
		
		for(Action action : actionArray){
			xmlb.append("<action>");
			xmlb.append("<id>").append(action.getId()).append("</id>");
			xmlb.append("<name>").append(XMLUtil.toSafeXMLString(action.getName())).append("</name>");
			xmlb.append("<endStatId>").append(action.getEndStatId()).append("</endStatId>");
			xmlb.append("<assignToMore>").append(action.getAssignToMore()).append("</assignToMore>");
			xmlb.append("<nextActionRoles>").append(flow.queryNextActionRoleIdsByActionId(action.getId())).append("</nextActionRoles>");
			xmlb.append("<isEndAction>").append(flow.isEndAction(action.getId())).append("</isEndAction>");
			
			String[] userArray = null;
			userArray = flow.queryNodeStatAssignUsers(template.getId(), action.getEndStatId());
			if(userArray == null || userArray.length == 0){
				xmlb.append("<users/>");
			}
			else{
				xmlb.append("<users>");
				
				for(String user : userArray){
			StringBuffer userRoles = new StringBuffer();
			
			Role[] userRoleArray = flow.queryUserNodeRoles(user, template.getId());
			for(Role userRole : userRoleArray){
				if(userRoles.length() > 0){
					userRoles.append(",");
				}
				
				userRoles.append(userRole.getName());
			}
			
			String userAlias = CynthiaUtil.getUserAlias(user);
			xmlb.append("<user" + (userAlias != null ? " alias=\"" + XMLUtil.toSafeXMLString(userAlias) + "\"" : "") + ">").append(XMLUtil.toSafeXMLString(user + "[" + userRoles + "]")).append("</user>");
				}
				
				xmlb.append("</users>");
			}
			
			xmlb.append("</action>");
	
	}
		
		xmlb.append("</actions>");
	}
	
	//roles
	xmlb.append("<roles>");
	
	xmlb.append("<role>");
	xmlb.append("<id>").append(Role.everyoneUUID).append("</id>");
	xmlb.append("<name>").append(XMLUtil.toSafeXMLString(Role.everyoneName)).append("</name>");
	xmlb.append("</role>");
	
	Role[] roleArray = flow.queryUserNodeRoles(key.getUsername(), template.getId());
	if(roleArray != null){
		for(Role role : roleArray){
	xmlb.append("<role>");
	xmlb.append("<id>").append(role.getId()).append("</id>");
	xmlb.append("<name>").append(XMLUtil.toSafeXMLString(role.getName())).append("</name>");
	xmlb.append("</role>");
		}
	}
	
	xmlb.append("</roles>");
	
	xmlb.append("</root>");
	
	Document doc = XMLUtil.string2Document(xmlb.toString(), "UTF-8");
	
	Node rootNode = XMLUtil.getSingleNode(doc, "root");
	
	Node templateNode =XMLUtil.getSingleNode(rootNode, "template");
	
	Node layoutNode = XMLUtil.getSingleNode(templateNode,"layout");
	
	//Node validColumnsNode =XMLUtil.getSingleNode(templateNode, "validColumns");
	rootNode.removeChild(templateNode);
	
	rootNode.appendChild(layoutNode);
	//rootNode.appendChild(validColumnsNode);
	
	List<Node> rowNodes = XMLUtil.getNodes(layoutNode, "rows/row");
	for(Node rowNode : rowNodes)
	{
		List<Node> columnNodes = XMLUtil.getNodes(rowNode, "column");
		for(Node columnNode : columnNodes)
		{
	List<Node> fieldNodeList = XMLUtil.getNodes(columnNode, "field");
	for(Node fieldNode : fieldNodeList){
		Node typeNode = XMLUtil.getSingleNode(fieldNode, "type");
		typeNode.setTextContent(typeNode.getTextContent().split("\\_")[1]);
		Node fieldIdNode = XMLUtil.getSingleNode(fieldNode,"id");
		Node dataTypeNode = XMLUtil.getSingleNode(fieldNode, "dataType");
		if(dataTypeNode.getTextContent().length() > 0){
	dataTypeNode.setTextContent(dataTypeNode.getTextContent().split("\\_")[1]);
		}
		
		List<Node> optionNodeList = XMLUtil.getNodes(fieldNode, "options/option");
		String fieldId = fieldIdNode.getTextContent();
		
		for(Node optionNode : optionNodeList){
	Node forbiddenNode = XMLUtil.getSingleNode(optionNode, "forbidden");
	forbiddenNode.setTextContent(forbiddenNode.getTextContent().split("\\_")[1]);
		}
	
		///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		StringBuffer controlHiddenFields = new StringBuffer();
		Node controlHiddenFieldsIdsNode = XMLUtil.getSingleNode(fieldNode, "controlHiddenFields");
		List<Node> controlHiddenFieldsIdList =  XMLUtil.getNodes(controlHiddenFieldsIdsNode, "controlHiddenField");
		for(Node controlHiddenField : controlHiddenFieldsIdList){
		if(controlHiddenFields.length() > 0){
		controlHiddenFields.append(",");
		}
		
		controlHiddenFields.append(controlHiddenField.getTextContent());
		}
		XMLUtil.removeAll(controlHiddenFieldsIdsNode);
		controlHiddenFieldsIdsNode.setTextContent(controlHiddenFields.toString());
		
		StringBuffer controlHiddenStates = new StringBuffer();
		Node controlHiddenStatesIdsNode = XMLUtil.getSingleNode(fieldNode, "controlHiddenStates");
		List<Node> controlHiddenStatesIdList =  XMLUtil.getNodes(controlHiddenStatesIdsNode, "controlHiddenState");
		for(Node controlHiddenState : controlHiddenStatesIdList){
		if(controlHiddenStates.length() > 0){
		controlHiddenStates.append(",");
		}
		
		controlHiddenStates.append(controlHiddenState.getTextContent());
		}
		XMLUtil.removeAll(controlHiddenStatesIdsNode);
		controlHiddenStatesIdsNode.setTextContent(controlHiddenStates.toString());
		///////////////////////////////////////////////////////////////////////////////////////////////////////////////////

		
		//controlActionIds
		StringBuffer controlActionIds = new StringBuffer();
		Node controlActionIdsNode = XMLUtil.getSingleNode(fieldNode, "controlActionIds");
		List<Node> controlActionIdNodeList = XMLUtil.getNodes(controlActionIdsNode, "controlActionId");
		for(Node controlActionIdNode : controlActionIdNodeList){
	if(controlActionIds.length() > 0){
		controlActionIds.append(",");
		}
	
	controlActionIds.append(controlActionIdNode.getTextContent());
		}
		
		XMLUtil.removeAll(controlActionIdsNode);
		controlActionIdsNode.setTextContent(controlActionIds.toString());
		
		//controlRoleIds
		StringBuffer controlRoleIds = new StringBuffer();
		Node controlRoleIdsNode = XMLUtil.getSingleNode(fieldNode, "controlRoleIds");
		List<Node> controlRoleIdNodeList = XMLUtil.getNodes(controlRoleIdsNode, "controlRoleId");
		for(Node controlRoleIdNode : controlRoleIdNodeList){
	if(controlRoleIds.length() > 0){
		controlRoleIds.append(",");
		}
	
	controlRoleIds.append(controlRoleIdNode.getTextContent());
		}
		
		XMLUtil.removeAll(controlRoleIdsNode);
		controlRoleIdsNode.setTextContent(controlRoleIds.toString());
	}
		}
	}
	
	out.println(XMLUtil.document2String(doc, "UTF-8"));

      out.write(_jsp_string1, 0, _jsp_string1.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 7170261747151080670L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("task/initStartActions.jsp"), 994534392786475380L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  static {
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string1 = "\r\n".toCharArray();
  }
}
