/*
 * JSP generated by Resin-3.1.12 (built Mon, 29 Aug 2011 03:22:08 PDT)
 */

package _jsp._task;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import com.sogou.qadev.service.cynthia.util.ArrayUtil;
import com.sogou.qadev.service.cynthia.service.ProjectInvolveManager;
import com.sogou.qadev.service.cynthia.service.ConfigManager;
import com.sogou.qadev.service.cynthia.service.impl.DataFilterMemory;
import com.sogou.qadev.service.cynthia.service.TableRuleManager;
import java.util.LinkedHashSet;
import com.sogou.qadev.service.cynthia.util.CynthiaUtil;
import com.sogou.qadev.service.cynthia.util.FileUtil;
import java.util.HashMap;
import com.sogou.qadev.service.cynthia.dao.DataAccessSessionMySQL;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.util.Map;
import com.sogou.qadev.service.cynthia.bean.QueryCondition;
import com.sogou.qadev.service.cynthia.util.FilterDataAssembleUtil;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import com.sogou.qadev.service.cynthia.service.FilterQueryManager;
import com.sogou.qadev.service.cynthia.bean.Attachment;
import com.sogou.qadev.service.cynthia.bean.Option;
import com.sogou.qadev.service.cynthia.bean.Field.DataType;
import com.sogou.qadev.service.cynthia.bean.Field.Type;
import com.sogou.qadev.service.cynthia.bean.Field;
import com.sogou.qadev.service.cynthia.service.DbPoolConnection;
import com.sogou.qadev.service.cynthia.bean.Key;
import com.sogou.qadev.service.cynthia.factory.DataAccessFactory;
import com.sogou.qadev.service.cynthia.service.DataAccessSession;
import com.sogou.qadev.service.cynthia.bean.UUID;
import com.sogou.qadev.service.cynthia.bean.Data;
import com.sogou.qadev.service.cynthia.bean.Flow;
import com.sogou.qadev.service.cynthia.bean.Filter;
import com.sogou.qadev.service.cynthia.bean.Stat;
import com.sogou.qadev.service.cynthia.bean.Template;
import java.net.URLEncoder;
import com.sogou.qadev.service.cynthia.util.ConfigUtil;
import com.sogou.qadev.service.cynthia.util.CommonUtil;
import com.sogou.qadev.service.cynthia.util.XMLUtil;
import org.w3c.dom.Document;
import org.w3c.dom.Node;
import org.w3c.dom.Element;
import java.util.ArrayList;
import java.util.List;
import java.net.URLDecoder;

public class _searchtask__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/json;charset=utf-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
	response.setHeader("Cache-Control","no-cache"); //Forces caches to obtain a new copy of the page from the origin server
	response.setHeader("Cache-Control","no-store"); //Directs caches not to store the page under any circumstance
	response.setDateHeader("Expires", 0); //Causes the proxy cache to see the page as "stale"
	response.setHeader("Pragma","no-cache"); //HTTP 1.0 backward compatibility

	out.clear();
	
	request.setCharacterEncoding("utf-8");

	Key key = (Key)session.getAttribute("key");
	Long keyId = (Long)session.getAttribute("kid");
	String username = request.getParameter("username");

	if(keyId == null || keyId <= 0 || key == null){
		response.sendRedirect(ConfigUtil.getCynthiaWebRoot());
		return;
	}

	if(key!=null)
		username = key.getUsername();

	String searchKey = URLDecoder.decode(request.getParameter("searchKey"),"UTF-8");
	String filterIdStr = request.getParameter("filterId");
	String searchType = request.getParameter("searchType");
	String templateIdStr = request.getParameter("template");

	int start = Integer.parseInt(request.getParameter("start"));
	int limit = Integer.parseInt(request.getParameter("limit"));
	String sort = request.getParameter("sort");
	String dir = request.getParameter("dir");
	
	int	pagenum        = (start/limit) + 1;
	int	count          = limit;

	if(searchType==null||"".equals(searchType))
	{
		response.sendRedirect(ConfigUtil.getCynthiaWebRoot());
		return;
	}

	Set<String> displayFieldsName = new HashSet<String>();
	int totalCount = 0;
	List<Data> dataList = new ArrayList<Data>();
	Set<String> notNewTaskIdSet = new HashSet<String>();
	Map<String,String> userClassifyDataMap = new HashMap<String,String>();
	boolean isSysFilter = true;
	DataAccessSession das = DataAccessFactory.getInstance().createDataAccessSession(username,keyId);
	
	if(filterIdStr == null || filterIdStr.length() == 0){
		displayFieldsName.addAll(Arrays.asList(new String[]{"\u6807\u9898","\u63cf\u8ff0","\u521b\u5efa\u65f6\u95f4","\u6307\u6d3e\u4eba","\u72b6\u6001","\u4fee\u6539\u65f6\u95f4","\u521b\u5efa\u4eba"}));
		//\u6ca1\u8bbe\u7f6e\u8fc7\u6ee4\u5668\uff0c\u5219\u5168\u5c40\u67e5\u8be2
		List<String> dataTable = TableRuleManager.getInstance().getAllDataTables();
		StringBuffer sqlBuffer = new StringBuffer();
		StringBuffer whereBuffer = new StringBuffer();
		if(searchKey != null && searchKey.length() >0 ){
			if(searchType.equals("id")){
				whereBuffer.append(" where ").append(searchType).append(" in (").append(searchKey).append(")");
			}else{
				whereBuffer.append(" where ").append(searchType).append(" like '%").append(searchKey).append("%'");
			}
			
			if(ConfigManager.getProjectInvolved()){
				Set<String> allCompanyUser = ProjectInvolveManager.getInstance().getCompanyUserMails(key.getUsername());
				StringBuffer userBuffer = new StringBuffer();
				if(allCompanyUser.size() > 0){
					for(String user : allCompanyUser){
						userBuffer.append(userBuffer.length() > 0 ? "," : "").append("'").append(user).append("'");
					}
					whereBuffer.append(" and createUser in (").append(userBuffer.toString()).append(") ");
				}
			}
		}
		
		for(String tableName : dataTable){
			sqlBuffer.append(sqlBuffer.length() > 0 ? " union " :"").append(" select id , templateId,title,description,createTime, assignUser,statusId,lastModifyTime,createUser from ").append(tableName)
			.append(whereBuffer);
		}
		String orderField = DataFilterMemory.getDbColName(sort, null);
		if(orderField != null && orderField.length() > 0)
			sqlBuffer.append(" order by ").append(DataFilterMemory.getDbColName(sort, null)).append( " " + dir);
		
		List<Data> allData = new DataAccessSessionMySQL().queryDatas(sqlBuffer.toString(), false, null);
		
		totalCount = allData.size();
		if(totalCount > 0){
			int endIndex = start + limit;
			if(endIndex > allData.size())
				endIndex = allData.size();
			dataList = allData.subList(start, endIndex);
		}
		
	}else{
		UUID filterId = DataAccessFactory.getInstance().createUUID(filterIdStr);
		UUID templateTypeId =null;
		UUID templateId = null;
		
		Filter filter = das.queryFilter(filterId);

		if(filter == null)
			return;
		
		displayFieldsName.addAll(Arrays.asList(FilterQueryManager.getDisplayFields(filter.getXml(), das)));
		isSysFilter = FilterQueryManager.isSysFilter(filterIdStr);

		if(!isSysFilter){
			templateId = FilterQueryManager.getFilterTemplateId(filter);
		}

		List<QueryCondition> queryConList = new ArrayList<QueryCondition>();
		QueryCondition queryCon = new QueryCondition(searchType,"like", "'%" +searchKey + "%'");
		queryConList.add(queryCon);

		if (isSysFilter) {
			FilterQueryManager.initFilterEnv(filter,keyId, key.getUsername(), null, das);
		}

		String sql = DataFilterMemory.getFilterSql(filter.getXml(), null , queryConList);

		sql = CynthiaUtil.cancelGroupOrder(sql);
		
		totalCount = DbPoolConnection.getInstance().getSearchResultCount(sql);

		sql = DataFilterMemory.getQuerySql(sql, pagenum,count,sort,dir,templateId == null ? null : templateId.getValue());
		dataList = new DataAccessSessionMySQL().queryDatas(sql, false, templateId);

	}
	
	userClassifyDataMap = das.getUserClassifyDataMap(username);
	StringBuffer result = new StringBuffer();
	result.append("{");
	result.append("\"totalCount\":\"").append(totalCount).append("\",\"rows\":[");

	result.append(FilterQueryManager.assembleFilterDataJson(displayFieldsName.toArray(new String[0]),dataList,notNewTaskIdSet,userClassifyDataMap , das , isSysFilter));

	result.append("]");
	result.append("}");

	out.print(result.toString());

      out.write('\n');
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 7170261747151080670L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("task/searchTask.jsp"), -2264537433892572037L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string0;
  static {
    _jsp_string0 = "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n".toCharArray();
  }
}
