/*
 * JSP generated by Resin-3.1.12 (built Mon, 29 Aug 2011 03:22:08 PDT)
 */

package _jsp._tree;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import com.sogou.qadev.service.cynthia.util.ArrayUtil;
import com.sogou.qadev.service.cynthia.service.ErrorManager.ErrorType;
import com.sogou.qadev.service.cynthia.service.ErrorManager;
import com.sogou.qadev.service.cynthia.bean.Timer;
import com.sogou.qadev.service.cynthia.bean.Key;
import java.util.*;
import com.sogou.qadev.service.cynthia.service.DataAccessSession;
import com.sogou.qadev.service.cynthia.service.DataAccessSession.ErrorCode;
import com.sogou.qadev.service.cynthia.factory.DataAccessFactory;
import com.sogou.qadev.service.cynthia.bean.Filter;
import com.sogou.qadev.service.cynthia.bean.JSTree;
import com.sogou.qadev.service.cynthia.bean.UUID;
import com.sogou.qadev.service.cynthia.util.ConfigUtil;
import java.sql.Timestamp;
import com.sogou.qadev.service.cynthia.util.XMLUtil;
import org.w3c.dom.*;
import javax.xml.parsers.*;

public class _jstree__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("application/x-json; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
response.setHeader("Cache-Control","no-cache"); //Forces caches to obtain a new copy of the page from the origin server
response.setHeader("Cache-Control","no-store"); //Directs caches not to store the page under any circumstance
response.setDateHeader("Expires", 0); //Causes the proxy cache to see the page as "stale"
response.setHeader("Pragma","no-cache"); //HTTP 1.0 backward compatibility    

out.clear();

Key key = (Key)session.getAttribute("key");
Long keyId = (Long)session.getAttribute("kid");

if(keyId == null || keyId <= 0 || key == null){
	response.sendRedirect(ConfigUtil.getCynthiaWebRoot());
	return;
}

String operation = request.getParameter("operation");
String nodeIdStr = request.getParameter("id");

if(operation==null||(!"updateFavorites".equals(operation)&&nodeIdStr==null))
{
	response.sendRedirect(ConfigUtil.getCynthiaWebRoot());
	return;
}

DataAccessSession das = DataAccessFactory.getInstance().createDataAccessSession(key.getUsername(), keyId);
String success = "{\"status\":1}";
String error = "{\"status\":0}";

if("get_children".equals(operation)){
	
	if(nodeIdStr.indexOf("filter")>=0)
		return;
	
	List<JSTree> list = null;
	JSTree localNode = null;
	List<Filter> folderFilters = null;
	Filter[] userFocusFilters = null;
	List<Filter> userFocusFiltersList = null;
	
	//\u7ecf\u5e38\u8bbf\u95ee
	if(nodeIdStr.indexOf("favorite")>=0)
	{
		String[] favoriteFilters = das.queryFavoriteFilters(key.getUsername());
		StringBuffer favJson = new StringBuffer();
		boolean flag = true;
		favJson.append("[");
		for(int i=0;i<favoriteFilters.length;i++)
		{
			Filter tempFilter = das.queryFilter(DataAccessFactory.getInstance().createUUID(favoriteFilters[i]));
			if(tempFilter!=null)
			{
				if(flag)
				{
					if(tempFilter.getCreateUser().equals(key.getUsername()))
					{
						favJson.append("{\"attr\":{\"id\":\"node_filter_"+tempFilter.getId()+"\",\"rel\":\"default\"},\"data\":\""+tempFilter.getName()+"\",\"state\":\"opened\"}");
					}else
					{
						favJson.append("{\"attr\":{\"id\":\"node_filter_"+tempFilter.getId()+"\",\"rel\":\"others\"},\"data\":\""+tempFilter.getName()+"\",\"state\":\"opened\"}");
					}
					
					flag = false;
				}else
				{
					if(tempFilter.getCreateUser().equals(key.getUsername()))
					{
						favJson.append(",{\"attr\":{\"id\":\"node_filter_"+tempFilter.getId()+"\",\"rel\":\"default\"},\"data\":\""+tempFilter.getName()+"\",\"state\":\"opened\"}");
					}else
					{
						favJson.append(",{\"attr\":{\"id\":\"node_filter_"+tempFilter.getId()+"\",\"rel\":\"others\"},\"data\":\""+tempFilter.getName()+"\",\"state\":\"opened\"}");
					}
				}
			}
		}
		favJson.append("]");
		out.println(favJson.toString());
		return;
	}
	
	int nodeId = Integer.parseInt(nodeIdStr);
	list = das.queryChilderNodes(nodeId,key.getUsername());  //\u5b50\u76ee\u5f55
	localNode = das.queryJSTreeNodeById(nodeId); //\u5f53\u524d\u76ee\u5f55
	folderFilters = new ArrayList<Filter>();
	userFocusFilters = das.queryFocusFilters(key.getUsername());
	userFocusFiltersList = Arrays.asList(userFocusFilters);
	if(nodeId==1)
	{
		list = das.queryRootNode(nodeId);
		JSTree rootNode = list.get(0);
		StringBuffer rootJson = new StringBuffer();
		rootJson.append("[");
		rootJson.append("{\"attr\":{\"id\":\"node_"+rootNode.getId()+"\",\"rel\":\"folder\"},\"data\":\""+rootNode.getTitle()+"\",\"state\":\"closed\"}");
		rootJson.append(",{\"attr\":{\"id\":\"node_favorite\",\"rel\":\"folder\"},\"data\":\"\u6700\u5e38\u8bbf\u95ee\",\"state\":\"closed\"}");
		rootJson.append("]");
		out.println(rootJson.toString());
		return;
	}else if(localNode.getParentId()==1)
	{
		List<String> allFolderFilters = das.queryAllFolderFilters(key.getUsername());
		List<String> defaultFilters = das.queryDefaultFilters(key.getUsername());
		for(String filterIdStr : defaultFilters)
		{
			for(Filter filter : userFocusFilters)
			{
				if(filter.getId().toString().equals(filterIdStr))
				{
					folderFilters.add(filter);
					break;
				}
			}
		}
		
		for(Filter filter:userFocusFilters)
		{
			if(!allFolderFilters.contains(filter.getId().toString())&&!defaultFilters.contains(filter.getId().toString()))
			{
				folderFilters.add(filter);
			}
		}
		
	}else
	{
		List<String> folderFiltersStr = das.queryFolderFilters(nodeId);
		
		for(String filterIdStr : folderFiltersStr)
		{
			for(Filter filter : userFocusFilters)
			{
				if(filter.getId().toString().equals(filterIdStr))
				{
					folderFilters.add(filter);
					break;
				}
			}	
		}
		
	}
	
	int count = list.size()+folderFilters.size();
	int i = 0;
	StringBuffer json = new StringBuffer();
	json.append("[");
	for(JSTree treeNode:list)
	{
		if(i==0)
		{
			json.append("{\"attr\":{\"id\":\"node_"+treeNode.getId()+"\",\"rel\":\"folder\"},\"data\":\""+treeNode.getTitle()+"\",\"state\":\"closed\"}");
		}else
		{
			json.append(",{\"attr\":{\"id\":\"node_"+treeNode.getId()+"\",\"rel\":\"folder\"},\"data\":\""+treeNode.getTitle()+"\",\"state\":\"closed\"}");
		}
		i++;
	}
	for(Filter folderFilter : folderFilters)
	{
		if(i==0)
		{	
			if(folderFilter.getCreateUser().equals(key.getUsername()))
			{
				json.append("{\"attr\":{\"id\":\"node_filter_"+folderFilter.getId()+"\",\"rel\":\"default\"},\"data\":\""+folderFilter.getName()+"\",\"state\":\"opened\"}");
			}else
			{
				json.append("{\"attr\":{\"id\":\"node_filter_"+folderFilter.getId()+"\",\"rel\":\"others\"},\"data\":\""+folderFilter.getName()+"\",\"state\":\"opened\"}");
			}
		}else
		{
			if(folderFilter.getCreateUser().equals(key.getUsername()))
			{
				json.append(",{\"attr\":{\"id\":\"node_filter_"+folderFilter.getId()+"\",\"rel\":\"default\"},\"data\":\""+folderFilter.getName()+"\",\"state\":\"opened\"}");
			}else
			{
				json.append(",{\"attr\":{\"id\":\"node_filter_"+folderFilter.getId()+"\",\"rel\":\"others\"},\"data\":\""+folderFilter.getName()+"\",\"state\":\"opened\"}");
			}		
		}
		i++;
	}
	
	json.append("]");
	out.println(json.toString());
	
}else if("create_node".equals(operation))
{
	String positionStr = request.getParameter("position");
	String title  = request.getParameter("title");
	String type = request.getParameter("type");
	
	if(nodeIdStr == null||"".equals(nodeIdStr))
	{
		out.println("{\"status\":0,\"msg\":\"ID\u4e0d\u5408\u6cd5,\u8bf7\u5237\u65b0\u540e\u5c1d\u8bd5\uff01\"}");
		return;
	}
	//filter\u4ee5\u53ca\u6700\u957f\u8bbf\u95ee\u4e0b\u4e0d\u5141\u8bb8\u65b0\u5efa\u76ee\u5f55
	if(nodeIdStr.indexOf("filter")>=0||nodeIdStr.indexOf("favorite")>=0)
	{
		out.println("{\"status\":0,\"msg\":\"\u8be5\u9879\u76ee\u4e0b\u65e0\u6cd5\u65b0\u5efa\u76ee\u5f55\"}");
		return;
	}
	if("default".equals(type))
	{   //\u8868\u793a\u65b0\u5efa\u8fc7\u6ee4\u5668
		Filter filter = null;
		filter = das.createFilter(key.getUsername(), new Timestamp(System.currentTimeMillis()), null);
		filter.setName(title);
		filter.setXml("");
		filter = das.addFilter(filter);//das.updateFilter(filter);
		
		if(filter!=null)
		{
			if(!"6".equals(nodeIdStr))
			{
				das.addFilterToFolder(filter.getId().toString(),Integer.parseInt(nodeIdStr));
			}
			das.addUserFocusFilter(key.getUsername(), filter.getId());
			out.println("{\"status\":1,\"id\":"+filter.getId()+"}");
		}else
		{
			out.println("{\"status\":0,\"id\":0}");
		}
		
	}else if(positionStr!=null&&!"".equals(positionStr))
	{
		int position = Integer.parseInt(positionStr);
		int parentId = Integer.parseInt(nodeIdStr);
		int result = das.addJSTreeNode(parentId,position,title,key.getUsername());
		if(result>0){
			out.println("{\"status\":1,\"id\":"+result+"}");
		}else{
			out.println("{\"status\":0,\"id\":0}");
		}
		
	}else
	{
		response.sendRedirect(ConfigUtil.getCynthiaWebRoot());
		return;	
	} 
	
}else if("remove_node".equals(operation))
{
	boolean result;
	String parentIdStr = request.getParameter("parentId");
	if(parentIdStr!=null&&(parentIdStr.indexOf("favorite")>=0))
	{//\u5982\u679c\u5220\u9664\u7684\u662f\u6700\u5e38\u8bbf\u95ee\u7684filter
		nodeIdStr = nodeIdStr.replace("filter_", "");
		result = das.removeFavoriteFilter(key.getUsername(), nodeIdStr);
		if(result)
		{
			out.println("{\"status\":1,\"msg\":\"\u5220\u9664\u6210\u529f\"}");
		}else
		{
			out.println("{\"status\":0,\"msg\":\"\u5220\u9664\u5931\u8d25\"}");
		}
		
	}else if(nodeIdStr.indexOf("filter")>=0)
	{
		//\u8868\u793a\u5220\u9664\u7684\u662f\u7b5b\u9009\u5668
		String filterIdStr = nodeIdStr.replace("filter_", "");
		UUID filterId = DataAccessFactory.getInstance().createUUID(filterIdStr);
		Filter filter = das.queryFilter(filterId);
		if(filter.getCreateUser().equals(key.getUsername()))
		{
				das.removeUserFocusFilter(filterId);
 				ErrorCode errorCode = das.removeFilter(filterId);
				
				if(errorCode.equals(ErrorCode.success))
				{
					out.println("{\"status\":1,\"msg\":\"\u5220\u9664\u6210\u529f\"}");
				}else
				{
					out.println("{\"status\":0,\"msg\":\"\u5220\u9664\u8fc7\u6ee4\u5668\u5931\u8d25\"}");
				}
		}else
		{
			das.removeUserFocusFilter(key.getUsername(),filterId);
			das.removeFavoriteFilter(key.getUsername(),filterIdStr);
			out.println("{\"status\":1,\"msg\":\"\u53d6\u6d88\u6210\u529f\"}");
		}
		
		
	}else
	{
		int nodeId = Integer.parseInt(nodeIdStr);
		result = das.removJSTreeNode(nodeId,key.getUsername());
		if(result)
		{
			out.println("{\"status\":1,\"msg\"\"\u5220\u9664\u6210\u529f\"}");
		}else
		{
			out.println("{\"status\":0,\"msg\":\"\u5220\u9664\u5931\u8d25\"}");
		}
	}
	
	
}else if("move_node".equals(operation))
{
	String refIdStr = request.getParameter("ref");
	String positionStr = request.getParameter("position");
	String title = request.getParameter("title");
	String copy = request.getParameter("copy");
	String parentIdStr = request.getParameter("parentId");
	String parentChildrenIdsStr = request.getParameter("parentChildrenIds");
	String refChildrenIdsStr = request.getParameter("refChildrenIds");
	boolean result = false;
	
	 if(refIdStr==null||positionStr==null)
	{
		response.sendRedirect(ConfigUtil.getCynthiaWebRoot());
		return;	
	}
	 if(refIdStr.indexOf("filter")>=0)
	 {
		 result = false;
	 }else if(refIdStr.indexOf("left_tree")>=0)
	 {
		 result = false;
	 }else if(nodeIdStr.indexOf("favorite")>=0)
	 {
		 result = false;
	 }else if(nodeIdStr.indexOf("filter")>=0&&(parentIdStr.indexOf("favorite")>=0))
	 {
		 result = false;
	 }else if(nodeIdStr.indexOf("favorite")>=0)
	 {
		 result = false;
	 }else if(refIdStr.indexOf("favorite")>=0)
	 {//\u65b0\u589e\u6700\u5e38\u8bbf\u95ee
		 //result = das.addFavoriteFilter(key.getUsername(),nodeIdStr.replace("filter_", ""));
		 result = das.updataFavoriteFilters(refChildrenIdsStr,key.getUsername());
	 }else if(nodeIdStr.indexOf("filter")>=0)
	 {
		 nodeIdStr = nodeIdStr.replace("filter_", "");
		 int nodeId = Integer.parseInt(nodeIdStr);
		 int refId = Integer.parseInt(refIdStr);
		 int parentId = Integer.parseInt(parentIdStr);
		 if(refId == 6)
		 {
	 		//result = das.removeFilterId(nodeId, parentId);
			 result = das.updateDefaultFilters(key.getUsername(),refChildrenIdsStr);
			 result = das.updateFilterOrders(parentId,key.getUsername(),parentChildrenIdsStr)&&result;
		 }else if(parentId == 6)
		 {
		 	result = das.updateFilterOrders(refId,key.getUsername(),refChildrenIdsStr);
		 	result = das.updateDefaultFilters(key.getUsername(),parentChildrenIdsStr);
		 }else
		 {
			 //result = das.moveFilterNode(nodeId, refId, parentId);
			 result = das.updateFilterOrders(refId,key.getUsername(),refChildrenIdsStr);
			 result = das.updateFilterOrders(parentId,key.getUsername(),parentChildrenIdsStr)&&result;
		 }
	 }else
	 {
		 	int nodeId = Integer.parseInt(nodeIdStr);
			int position = Integer.parseInt(positionStr);
			int refId = Integer.parseInt(refIdStr);
			if("0".equals(copy))
			{
				result = das.moveJSTreeNode(nodeId,refId,position,title,false,key.getUsername());
			}else if("1".equals(copy))
			{
				result = das.moveJSTreeNode(nodeId,refId,position,title,true,key.getUsername());
			}	 
	 }
	 
	out.println("{\"status\":1,\"msg\":\"\u66f4\u65b0\u6210\u529f\"}");
	
}else if("rename_node".equals(operation))
{
	String title = request.getParameter("title");
	if(nodeIdStr.indexOf("filter")>=0)
	{
		String filterIdStr = nodeIdStr.replace("filter_","");
		UUID filterId = DataAccessFactory.getInstance().createUUID(filterIdStr);
		Filter filter = das.queryFilter(filterId);
		filter.setName(title);
		das.updateFilter(filter);
		out.println("{\"status\":1}");
	}else
	{
		int nodeId = Integer.parseInt(nodeIdStr);
   	 	boolean result = das.updateJSTreeNode(nodeId,title);
    	if(result)
		{
			out.println("{\"status\":1}");
		}else
		{
			out.println("{\"status\":0}");
		}
	}
}else if("verify".equals(operation))
{
    boolean result = true;
    if(nodeIdStr == null||"".equals(nodeIdStr))
    {
    	result = false;
    }else
    {
    	UUID filterId = DataAccessFactory.getInstance().createUUID(nodeIdStr);
    	Filter filter = das.queryFilter(filterId);
    	if(filter == null)
    	{
    		result = false;
    	}else if(filter.getXml()==null||"".equals(filter.getXml()))
    	{
    		result = true;
    	}else
    	{
    		Document	xmlDoc	= XMLUtil.string2Document(filter.getXml(), "UTF-8");
        	List<Node>	tempNodeList = XMLUtil.getNodes( xmlDoc, "/query/template" );
        	if(tempNodeList == null||tempNodeList.size()!=1)
        	{
        		result = false;
       		}else
        	{
        		result = true;
        	}
    	}
    }
    
    if(result)
    {
    	out.println(success);
    }else
    {
    	out.println(error);
    }
}else if("updateFavorites".equals(operation))
{
	String[] data = request.getParameterValues("id[]");
	boolean result = true;
	String filters = ArrayUtil.strArray2String(data);
	if(data == null)
		result = false;
	else
	{
		result = das.updataFavoriteFilters(filters,key.getUsername());
	}
	if(result)
		out.println(success);
	else
	 	out.println(error);
}else if("update_favorites".equals(operation))
{
	String positionStr = request.getParameter("position");
	String childrenIds = request.getParameter("childrenIds");
	if(positionStr==null)
	{
		out.println(error);
	}else
	{
		boolean result = das.updataFavoriteFilters(childrenIds,key.getUsername());
		//boolean result = das.updateFavoritesFilters(nodeIdStr,position,key.getUsername());
		if(result)
			out.println(success);
		else
	 		out.println(error);
	}
}else if("add_to_favorites".equals(operation))
{
	String filterId = request.getParameter("filterId");
	boolean result = das.addFavoriteFilter(key.getUsername(),nodeIdStr);
	if(result)
		out.println(success);
	else
	 	out.println(error);
}else if("update_filter_order".equals(operation))
{
	String parentIdStr = request.getParameter("parentId");
	String newOrders = request.getParameter("childrenIds");
	if(parentIdStr==null||"".equals(parentIdStr))
	{
		out.println(error);
		return;
	}
	if("6".equals(parentIdStr))
	{
		boolean result = das.updateDefaultFilters(key.getUsername(),newOrders);
		if(result)
			out.println(success);
		else
	 		out.println(error);
	}else
	{
		int parentId = Integer.parseInt(parentIdStr);
		boolean result = das.updateFilterOrders(parentId,key.getUsername(),newOrders);
		if(result)
			out.println(success);
		else
	 		out.println(error);
	}
}else if("copy".equals(operation))
{
	Filter srcFilter = das.queryFilter(DataAccessFactory.getInstance().createUUID(nodeIdStr));
	Filter newFilter = das.createFilter(key.getUsername(), new Timestamp(System.currentTimeMillis()), null);
	newFilter.setName(srcFilter.getName()+"new");
	newFilter.setXml(srcFilter.getXml());
	newFilter.setPublic(srcFilter.isPublic());
	newFilter.setVisible(srcFilter.isVisible());
	newFilter.setAnd(srcFilter.isAnd());
	newFilter = das.addFilter(newFilter); //das.updateFilter(filter);
	List<String> focusUsers = das.queryFocusUsersByFilter(srcFilter.getId());
	
	//\u590d\u5236\u5173\u6ce8\u4eba
	if(focusUsers != null && focusUsers.size() > 0){
		for(String user: focusUsers){
			if(user != null && user.length() > 0)
				das.addUserFocusFilter(user, newFilter.getId());
		}
	}
	
	//\u590d\u5236\u5b9a\u65f6\u5668\u90e8\u5206
	Timer[] allTimer = das.queryTimerByFilterId(srcFilter.getId());
	if(allTimer != null && allTimer.length > 0){
		Timer newTimer = das.createTimer(key.getUsername());
		Timer srcTimer = allTimer[0];
		newTimer.setActionId(srcTimer.getActionId());
		newTimer.setActionParam(srcTimer.getActionParam());
		newTimer.setDay(srcTimer.getDay());
		newTimer.setFilterId(newFilter.getId());
		newTimer.setHour(srcTimer.getHour());
		newTimer.setMinute(srcTimer.getMinute());
		newTimer.setMonth(srcTimer.getMonth());
		newTimer.setName(srcTimer.getName());
		newTimer.setRetry(srcTimer.getRetry());
		newTimer.setRetryAccount(srcTimer.getRetryAccount());
		newTimer.setRetryDelay(srcTimer.getRetryDelay());
		newTimer.setSecond(srcTimer.getSecond());
		newTimer.setStart(srcTimer.getStart());
		newTimer.setStatisticerId(srcTimer.getStatisticerId());
		newTimer.setWeek(srcTimer.getWeek());
		newTimer.setYear(srcTimer.getYear());
		
		ErrorCode errorCode = das.addTimer(newTimer);	
		if(!errorCode.equals(ErrorCode.success)){
			out.println(ErrorManager.getErrorXml(ErrorType.database_update_error));
			return;
		}
	}
	out.println("{\"status\":1,\"id\":"+newFilter.getId()+"}");
}

    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 7170261747151080670L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("tree/jsTree.jsp"), -7049471290490115483L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string0;
  static {
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
  }
}
